### ISSUE TITLE
Login not working IOS mobile devices

### ISSUE THREAD

**Issue by gabouh** [kellenmace/headless-wordpress-authentication-native-cookies#3]
I have implemented the login and it works but it doesn't work on IOS mobile devices, any clues why? am trying to debug it but no solutions yet.
Apparently the login is getting response SUCCESS but it not redirecting or setting the cookie.

**Comment by gabouh** [comment]
Somehow when doing migration to vercel the issue fixed itself. Weird, but now it works.

**Comment by monsieurnebo** [comment]
This is related to Apple doesn't allowing cross-domain cookies.

See the solution in this [issue](https://github.com/kellenmace/headless-wordpress-authentication-native-cookies/issues/4).
